#!/bin/bash -eux

REPOROOT="$(dirname "$(readlink -f "$0")")/.."
cd "${REPOROOT}"
git submodule update --init

cd external/mikanos-build/devenv
wget https://github.com/uchan-nos/mikanos-build/releases/download/v2.0/x86_64-elf.tar.gz
tar xvf x86_64-elf.tar.gz
rm x86_64-elf.tar.gz
